name: background_downloader
description: A multi-platform background file downloader and uploader. Define the task, enqueue and monitor progress

version: 8.5.2
repository: https://github.com/781flyingdutchman/background_downloader

environment:
#  sdk: ^3.0.0
#  flutter:  '>=3.0.0'
  sdk: '>=2.19.0 <=4.0.0'
#  flutter: '>=3.7.12-ohos'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  http: ^1.1.0
  path_provider: ^2.0.2
  path: ^1.8.1
  async: ^2.6.0
  mime: ^1.0.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  ohos:

dependency_overrides:
  path_provider:
    git:
      url: https://gitee.com/openharmony-sig/flutter_packages.git
      path: packages/path_provider/path_provider
  http: ^0.13.6
  flutter_lints: ^2.0.1
flutter:
  plugin:
    platforms:
      android:
        package: com.bbflight.background_downloader
        pluginClass: BDPlugin
      ios:
        pluginClass: BackgroundDownloaderPlugin
